Add mentor name
htmlacademy-javascript/1124279-keksobooking-25 pull request #1
Opened 2022-02-16 14:10 UTC by IvanPodorozhnyi

2022-02-16 17:06 UTC, Dima-Dim requested changes

2022-02-16 17:06 UTC, Dima-Dim commented on Readme.md
> +* Наставник: [Дмитрий Гуляев] (https://htmlacademy.ru/profile/dima).
Сейчас это выглядит вот так:
https://github.com/htmlacademy-javascript/1124279-keksobooking-25/blob/b49504927bbd557aacd94b8ab2e64918206e70b7/Readme.md
Нужно немного поправить чтобы ссылкой былы имя и фамилия.

2022-02-16 18:04 UTC, IvanPodorozhnyi commented on Readme.md
> +* Наставник: [Дмитрий Гуляев] (https://htmlacademy.ru/profile/dima).
Поправил.

2022-02-17 13:00 UTC, Dima-Dim approved these changes

2022-02-17 13:00 UTC, merged