create two function
htmlacademy-javascript/1124279-keksobooking-25 pull request #2
Opened 2022-02-21 15:59 UTC by IvanPodorozhnyi

2022-02-22 06:01 UTC, Dima-Dim requested changes

2022-02-22 06:01 UTC, Dima-Dim commented on js/main.js
> +    max = Math.random() * (max + 1);
Не нужно менять значения переменных которые пришли к нам в функцию. Здесь сама функция не большая и переменные, которые в неё приходят примитивы и вроде как всё можно, но лушче такое не практиковать.

2022-02-22 06:18 UTC, IvanPodorozhnyi commented on js/main.js
> +    max = Math.random() * (max + 1);
В задание было что если приходит равные значения и min больше max то придумайте поведение, мне кроме этого ничего в голову не пришло

2022-02-22 06:31 UTC, Dima-Dim commented on js/main.js
> +    max = Math.random() * (max + 1);
У нас нет ограничений на создание новых переменных.

2022-02-24 08:24 UTC, Dima-Dim requested changes

2022-02-24 08:24 UTC, Dima-Dim commented on js/main.js
> +    min = 0;
Не нужно переопределять переданные в функцию значения. Вообще нужно стараться ничего не переопределять это усложняет понимание того, с чем в каком месте ты имеешь дело.

2022-02-24 08:24 UTC, Dima-Dim commented on js/main.js
> +    [min, max] = [max, min];
Такой подход тоже усложняет понимание того что происходит в коде. Основная проблема - переопределение переменных по коду. Это плохой подход. Да, иногда без этого никак, но это явно не тот случай, нужно стремиться к написанию более простого и очевидного кода, потому что потом кому-то эти "ребусы" разгадывать придётся и таких случаев будет гораздо больше, чем случаев когда это пишется.

2022-02-26 08:52 UTC, merged